version: "3"
services:

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - mongo.env
    volumes:
    - ./mongo/data/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - mongo-express.env
    ports:
      - 8081:8081
    depends_on:
      - mongo

  admin:
    image: lazukin/admin-server:latest
    restart: on-failure
    ports:
      - 9003:9003

  client:
    image: lazukin/client-service:latest
    restart: on-failure
    env_file:
      - client-service.env
    depends_on:
      - admin
      - mongo
    ports:
    - 8080:8080